name: Run Cypress Tests

on:
  push:
    branches: [main]     # Tự động chạy khi có push lên nhánh main
  pull_request:
    branches: [main]     # Hoặc khi có pull request đến nhánh main

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Lấy mã nguồn từ GitHub
        uses: actions/checkout@v3

      - name: Cài Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Cài đặt thư viện npm
        run: npm install

      - name: Chạy Cypress test
        run: npx cypress run